/**
 * @file interr.c
 * @brief Interrupt service routines for the STM32F4 platform.
 * @author SDG2. Román Cárdenas (r.cardenas@upm.es) and Josué Pagán (j.pagan@upm.es)
 * @date 2026-01-01
 */
// Include HW dependencies:

#include "stm32f4_system.h"
#include "stm32f4_button.h"
#include "stm32f4_keyboard.h"

// Include headers of different port elements:

#include "port_system.h"
#include "port_button.h"
#include "port_keyboard.h"
#include "port_simone.h"

//------------------------------------------------------
// INTERRUPT SERVICE ROUTINES
//------------------------------------------------------

/**
 * @brief Interrupt service routine for the System tick timer (SysTick).
 *
 * @note This ISR is called when the SysTick timer generates an interrupt.
 * The program flow jumps to this ISR and increments the tick counter by one millisecond.
 * @warning **The variable `msTicks` must be declared volatile!** Just because it is modified by a call of an ISR, in order to avoid [*race conditions*](https://en.wikipedia.org/wiki/Race_condition). **Added to the definition** after *static*.
 *
 */
void SysTick_Handler(void)
{
    uint32_t msActual = port_system_get_millis(); // we get the current value of the system tick in milliseconds
    port_system_set_millis(msActual + 1);         // we set the msTicks variable to the current value increased by one
}

/**
 * @brief Check and handle the column interrupt for a given column index. This function is called from the EXTI IRQHandlers for each column.
 *
 * @param column_index
 */
void _check_column_interrupt(uint8_t column_index)
{
    GPIO_TypeDef *port = keyboards_arr[PORT_KEYBOARD_MAIN_ID].p_col_ports[column_index]; // We retrieve the port and pin of the column that generated the interruption
    uint16_t pin = keyboards_arr[PORT_KEYBOARD_MAIN_ID].p_col_pins[column_index];
    bool pulsado = stm32f4_system_gpio_read(port, pin); // We read the current state of the pin (HIGH or LOW) to know if it was released or pressed
    if (pulsado)
    {
        keyboards_arr[PORT_KEYBOARD_MAIN_ID].flag_key_pressed = true; // If the pin is HIGH, we update the flag of the pressed key of the corresponding keyboard to true
    }
    else
    {
        keyboards_arr[PORT_KEYBOARD_MAIN_ID].flag_key_pressed = false;         // If the pin is LOW, we update the flag of the pressed key of the corresponding keyboard to false
        keyboards_arr[PORT_KEYBOARD_MAIN_ID].col_idx_interrupt = column_index; // If the pin is LOW, we update the index of the column that generated the interruption for the corresponding keyboard
    }

    EXTI->PR = BIT_POS_TO_MASK(pin); // We clean the interruption register for the pin of the column that generated the interruption
}

/**
 * @brief This function handles Px10-Px15 global interrupts.
 *
 */
void EXTI15_10_IRQHandler(void)
{
    port_system_systick_resume(); // To resume the system tick in case it was suspended to save power while waiting for a keyboard event
                                  // To check if the interrupt has been generated by the pin of the user button
    if (EXTI->PR & BIT_POS_TO_MASK(buttons_arr[PORT_USER_BUTTON_ID].pin))
    {
        GPIO_TypeDef *port = buttons_arr[PORT_USER_BUTTON_ID].p_port; // We retrieve the values of the pin and its port
        uint16_t pin_IRQ = buttons_arr[PORT_USER_BUTTON_ID].pin;

        bool pulsado = stm32f4_system_gpio_read(port, pin_IRQ);   // We read the current state of the pin (HIGH or LOW) to know if it was released or pressed
        buttons_arr[PORT_USER_BUTTON_ID].flag_pressed = !pulsado; // If the pin is HIGH, we update the flag of the pressed button to false (not pressed), and if the pin is LOW, we update this flag to true (pressed)
        EXTI->PR = BIT_POS_TO_MASK(pin_IRQ);                      // We clean the interruption register
    }

    // To check if the interrupt has been generated by any of the columns of the keyboard
    if (EXTI->PR & BIT_POS_TO_MASK(keyboards_arr[PORT_KEYBOARD_MAIN_ID].p_col_pins[PORT_KEYBOARD_COL_1]))
    {
        _check_column_interrupt(PORT_KEYBOARD_COL_1); // To check if the interrupt has been generated by column 1 of the keyboard
    }
}

/**
 * @brief This function handles EXTI lines [9:5] interrupts.
 *
 */
void EXTI9_5_IRQHandler(void)
{
    port_system_systick_resume(); // To resume the system tick in case it was suspended to save power while waiting for a keyboard event
                                  // To check if the interrupt has been generated by column 0 or column 3 of the keyboard
    if (EXTI->PR & BIT_POS_TO_MASK(keyboards_arr[PORT_KEYBOARD_MAIN_ID].p_col_pins[PORT_KEYBOARD_COL_0]))
    {
        _check_column_interrupt(PORT_KEYBOARD_COL_0);
    }

    if (EXTI->PR & BIT_POS_TO_MASK(keyboards_arr[PORT_KEYBOARD_MAIN_ID].p_col_pins[PORT_KEYBOARD_COL_3]))
    {
        _check_column_interrupt(PORT_KEYBOARD_COL_3);
    }
}

/**
 * @brief This function handles EXTI line 4 interrupt.
 *
 */
void EXTI4_IRQHandler(void)
{
    port_system_systick_resume();                 // To resume the system tick in case it was suspended to save power while waiting for a keyboard event
    _check_column_interrupt(PORT_KEYBOARD_COL_2); // We check if the interruption was generated by column 2 of the keyboard
}

/**
 * @brief Interrupt service routine for the TIM3 timer.
 *
 */
void TIM5_IRQHandler(void)
{
    TIM5->SR &= ~TIM_SR_UIF;                                           // We clean the update flag of TIM5 to avoid that the interruption is generated again immediately after exiting the ISR
    port_keyboard_set_row_timeout_status(PORT_KEYBOARD_MAIN_ID, true); // We update the timeout flag of the corresponding keyboard
}

/**
 * @brief Interrupt service routine for the TIM3 timer.
 *
 */
void TIM3_IRQHandler(void)
{
    TIM3->SR &= ~TIM_SR_UIF;            // We clean the update flag of TIM3 to avoid that the interruption is generated again immediately after exiting the ISR
    port_simone_set_timer_status(true); // We update the timeout flag of simone to indicate that a timeout has occurred
}
